name: "Pu-Be Sandwich"
calc_type: "sandwich"
source_matdef:
  Pu-238: 1.0
source_density: 19.8   # g/cm^3
target_matdef:
  Be-9: 1.0
intermediate_layers:
  - matdef: {C: 1.0}
    density: 2.26
    thickness: 1.0e-4   # 1 micron
